export const TOOLS = [
  {
    id: "1",
    name: "CodeRabbit",
    variant: "CodeRabbit Pro",
    duration: "1M",
    category: "🔥 New & Premium",
    description: "Premium access to CodeRabbit Pro for 1M.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "Trending",
    status: "Active"
  },
  {
    id: "2",
    name: "CodeRabbit",
    variant: "CodeRabbit Pro",
    duration: "2M",
    category: "🔥 New & Premium",
    description: "Premium access to CodeRabbit Pro for 2M.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "Trending",
    status: "Active"
  },
  {
    id: "3",
    name: "Loom Business + AI",
    variant: "Business + AI",
    duration: "1Y",
    category: "🔥 New & Premium",
    description: "Premium access to Loom Business + AI for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "Trending",
    status: "Active"
  },
  {
    id: "4",
    name: "Wispr Flow",
    variant: "Wispr Flow Pro",
    duration: "1Y",
    category: "🔥 New & Premium",
    description: "Premium access to Wispr Flow Pro for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "Trending",
    status: "Active"
  },
  {
    id: "5",
    name: "Willow Voice",
    variant: "Willow Voice Pro",
    duration: "1Y",
    category: "🔥 New & Premium",
    description: "Premium access to Willow Voice Pro for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "Trending",
    status: "Active"
  },
  {
    id: "6",
    name: "PromptDrive.ai",
    variant: "PromptDrive.ai Teams",
    duration: "1Y",
    category: "🔥 New & Premium",
    description: "Premium access to PromptDrive.ai Teams for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "Trending",
    status: "Active"
  },
  {
    id: "7",
    name: "PromptDrive.ai Business (50 Seats)",
    variant: "Standard",
    duration: "1Y",
    category: "🔥 New & Premium",
    description: "Premium access to PromptDrive.ai Business (50 Seats) for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "Trending",
    status: "Active"
  },
  {
    id: "8",
    name: "PostHog",
    variant: "PostHog Scale",
    duration: "1Y",
    category: "🔥 New & Premium",
    description: "Premium access to PostHog Scale for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "Trending",
    status: "Active"
  },
  {
    id: "9",
    name: "Firecrawl",
    variant: "Firecrawl AI",
    duration: "50K Credits (1Y)",
    category: "🔥 New & Premium",
    description: "Premium access to Firecrawl AI for 50K Credits (1Y).",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "Trending",
    status: "Active"
  },
  {
    id: "10",
    name: "Vapi",
    variant: "Standard",
    duration: "$200 Credits (12M)",
    category: "🔥 New & Premium",
    description: "Premium access to Vapi for $200 Credits (12M).",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "Trending",
    status: "Active"
  },
  {
    id: "11",
    name: "Emergent Standard",
    variant: "Standard",
    duration: "1Y",
    category: "🔥 New & Premium",
    description: "Premium access to Emergent Standard for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "Trending",
    status: "Active"
  },
  {
    id: "12",
    name: "Manus AI Pro (6000 Credits)",
    variant: "Standard",
    duration: "1M",
    category: "🔥 New & Premium",
    description: "Premium access to Manus AI Pro (6000 Credits) for 1M.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "Trending",
    status: "Active"
  },
  {
    id: "13",
    name: "Reforge AI Build",
    variant: "Standard",
    duration: "1M",
    category: "🔥 New & Premium",
    description: "Premium access to Reforge AI Build for 1M.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "Trending",
    status: "Active"
  },
  {
    id: "14",
    name: "Sentry.io",
    variant: "Sentry.io Teams",
    duration: "1Y",
    category: "🔥 New & Premium",
    description: "Premium access to Sentry.io Teams for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "Trending",
    status: "Active"
  },
  {
    id: "15",
    name: "Sentry.io",
    variant: "Sentry.io Business",
    duration: "1Y",
    category: "🔥 New & Premium",
    description: "Premium access to Sentry.io Business for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "Trending",
    status: "Active"
  },
  {
    id: "16",
    name: "Beautiful.ai",
    variant: "Beautiful.ai Pro",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Beautiful.ai Pro for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "17",
    name: "Mobbin",
    variant: "Mobbin Pro",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Mobbin Pro for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "18",
    name: "ChatPRD",
    variant: "ChatPRD Pro",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to ChatPRD Pro for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "19",
    name: "Perplexity",
    variant: "Perplexity Pro",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Perplexity Pro for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "20",
    name: "Raycast",
    variant: "Raycast Pro",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Raycast Pro for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "21",
    name: "Superhuman",
    variant: "Superhuman Starter",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Superhuman Starter for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "22",
    name: "Linear",
    variant: "Linear Business",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Linear Business for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "23",
    name: "Granola",
    variant: "Granola Business",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Granola Business for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "24",
    name: "Magic Patterns Hobby",
    variant: "Standard",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Magic Patterns Hobby for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "25",
    name: "Wispr Flow",
    variant: "Wispr Flow Pro",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Wispr Flow Pro for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "26",
    name: "Webflow CMS",
    variant: "Standard",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Webflow CMS for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "27",
    name: "Webflow",
    variant: "Webflow Business",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Webflow Business for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "28",
    name: "Webflow",
    variant: "Webflow Growth",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Webflow Growth for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "29",
    name: "n8n",
    variant: "n8n Starter",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to n8n Starter for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "30",
    name: "Replit",
    variant: "Replit Core",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Replit Core for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "31",
    name: "Lovable Pro (100 Credits / Month)",
    variant: "Standard",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Lovable Pro (100 Credits / Month) for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "32",
    name: "ClickUp",
    variant: "ClickUp Enterprise",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to ClickUp Enterprise for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "33",
    name: "Cal.com",
    variant: "Cal.com Teams",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Cal.com Teams for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "34",
    name: "Cal.com",
    variant: "Cal.com Organization",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Cal.com Organization for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "35",
    name: "GitLab",
    variant: "GitLab Ultimate",
    duration: "12M",
    category: "⭐ Top Selling",
    description: "Premium access to GitLab Ultimate for 12M.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "36",
    name: "Postman",
    variant: "Postman Basic",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Postman Basic for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "37",
    name: "Zeplin",
    variant: "Zeplin Advanced",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Zeplin Advanced for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "38",
    name: "Backblaze Cloud",
    variant: "Backblaze Cloud Unlimited",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Backblaze Cloud Unlimited for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "39",
    name: "Bitwarden Premium +",
    variant: "Bitwarden Premium + Family",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Bitwarden Premium + Family for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "40",
    name: "Termly.io",
    variant: "Termly.io Starter",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Termly.io Starter for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "41",
    name: "Termly.io",
    variant: "Termly.io Pro+",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Termly.io Pro+ for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "42",
    name: "Hostinger Cloud",
    variant: "Hostinger Cloud Startup",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Hostinger Cloud Startup for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "43",
    name: "Pica",
    variant: "Pica Starter",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Pica Starter for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "44",
    name: "Framer",
    variant: "Framer Basic",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Framer Basic for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "45",
    name: "Framer",
    variant: "Framer Pro",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Framer Pro for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "46",
    name: "Figma",
    variant: "Figma Professional",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Figma Professional for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "47",
    name: "Intercom",
    variant: "Intercom Advanced",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Intercom Advanced for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "48",
    name: "Loom Business + AI",
    variant: "Business + AI",
    duration: "1Y",
    category: "⭐ Top Selling",
    description: "Premium access to Loom Business + AI for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "49",
    name: "Rezi",
    variant: "Rezi AI",
    duration: "Lifetime",
    category: "🎓 Career / Education",
    description: "Premium access to Rezi AI for Lifetime.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "50",
    name: "PNGTree Premium",
    variant: "Standard",
    duration: "Lifetime",
    category: "🎓 Career / Education",
    description: "Premium access to PNGTree Premium for Lifetime.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "51",
    name: "Enginemailer Free Forever (10K / Month)",
    variant: "Standard",
    duration: "Lifetime",
    category: "🎓 Career / Education",
    description: "Premium access to Enginemailer Free Forever (10K / Month) for Lifetime.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "52",
    name: "LinkedIn Career Premium",
    variant: "Standard",
    duration: "3M",
    category: "🎓 Career / Education",
    description: "Premium access to LinkedIn Career Premium for 3M.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "53",
    name: "LinkedIn Business Premium",
    variant: "Standard",
    duration: "3M",
    category: "🎓 Career / Education",
    description: "Premium access to LinkedIn Business Premium for 3M.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "54",
    name: "Scrimba",
    variant: "Scrimba Pro",
    duration: "1Y",
    category: "🎓 Career / Education",
    description: "Premium access to Scrimba Pro for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "55",
    name: "No Code MBA",
    variant: "No Code MBA Unlimited",
    duration: "1M",
    category: "🎓 Career / Education",
    description: "Premium access to No Code MBA Unlimited for 1M.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "56",
    name: "Whizlabs Premium",
    variant: "Standard",
    duration: "1M",
    category: "🎓 Career / Education",
    description: "Premium access to Whizlabs Premium for 1M.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "57",
    name: "Whizlabs Premium",
    variant: "Standard",
    duration: "1Y",
    category: "🎓 Career / Education",
    description: "Premium access to Whizlabs Premium for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "58",
    name: "AhaSlides Essentials",
    variant: "Standard",
    duration: "12M",
    category: "🎓 Career / Education",
    description: "Premium access to AhaSlides Essentials for 12M.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "59",
    name: "AhaSlides",
    variant: "AhaSlides Pro",
    duration: "12M",
    category: "🎓 Career / Education",
    description: "Premium access to AhaSlides Pro for 12M.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "60",
    name: "Kickresume Premium",
    variant: "Standard",
    duration: "1M",
    category: "🎓 Career / Education",
    description: "Premium access to Kickresume Premium for 1M.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "61",
    name: "Mangoosh GRE Premium",
    variant: "Standard",
    duration: "1M",
    category: "🎓 Career / Education",
    description: "Premium access to Mangoosh GRE Premium for 1M.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "62",
    name: "UFC FightPass",
    variant: "Standard",
    duration: "2M",
    category: "🎓 Career / Education",
    description: "Premium access to UFC FightPass for 2M.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "63",
    name: "Gemini AI Pro + 2TB Storage",
    variant: "Standard",
    duration: "18M",
    category: "🎓 Career / Education",
    description: "Premium access to Gemini AI Pro + 2TB Storage for 18M.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "64",
    name: "Adobe Creative Cloud",
    variant: "Adobe Creative Cloud Max",
    duration: "1Y",
    category: "🎨 AI & Design Tools",
    description: "Premium access to Adobe Creative Cloud Max for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "65",
    name: "Midjourney",
    variant: "Midjourney Pro",
    duration: "1M",
    category: "🎨 AI & Design Tools",
    description: "Premium access to Midjourney Pro for 1M.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "66",
    name: "Canva",
    variant: "Canva Creator",
    duration: "Lifetime",
    category: "🎨 AI & Design Tools",
    description: "Premium access to Canva Creator for Lifetime.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "67",
    name: "HubSpot",
    variant: "HubSpot Growth",
    duration: "1Y",
    category: "📈 Business & Marketing",
    description: "Premium access to HubSpot Growth for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "68",
    name: "Mailchimp Advanced (100K Credits)",
    variant: "Standard",
    duration: "1M",
    category: "📈 Business & Marketing",
    description: "Premium access to Mailchimp Advanced (100K Credits) for 1M.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "69",
    name: "SEMrush Guru Plan",
    variant: "Standard",
    duration: "1Y",
    category: "📈 Business & Marketing",
    description: "Premium access to SEMrush Guru Plan for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "70",
    name: "Google Drive 2TB Storage",
    variant: "Standard",
    duration: "1Y",
    category: "☁️ Cloud & Storage",
    description: "Premium access to Google Drive 2TB Storage for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "71",
    name: "Dropbox Professional 3TB Storage",
    variant: "Standard",
    duration: "1Y",
    category: "☁️ Cloud & Storage",
    description: "Premium access to Dropbox Professional 3TB Storage for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "72",
    name: "iCloud+ 2TB",
    variant: "Standard",
    duration: "1Y",
    category: "☁️ Cloud & Storage",
    description: "Premium access to iCloud+ 2TB for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "73",
    name: "Jira Premium (Per Seat)",
    variant: "Standard",
    duration: "1Y",
    category: "🧩 Dev & Team Tools",
    description: "Premium access to Jira Premium (Per Seat) for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "74",
    name: "GitHub Enterprise (Per Seat)",
    variant: "Standard",
    duration: "1Y",
    category: "🧩 Dev & Team Tools",
    description: "Premium access to GitHub Enterprise (Per Seat) for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "75",
    name: "Slack Enterprise",
    variant: "Slack Enterprise Grid",
    duration: "1Y",
    category: "🧩 Dev & Team Tools",
    description: "Premium access to Slack Enterprise Grid for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "76",
    name: "AutoCAD 2024",
    variant: "AutoCAD 2024 Professional",
    duration: "1Y",
    category: "🛠 3D / CAD Engineering",
    description: "Premium access to AutoCAD 2024 Professional for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "77",
    name: "SolidWorks Premium",
    variant: "Standard",
    duration: "1Y",
    category: "🛠 3D / CAD Engineering",
    description: "Premium access to SolidWorks Premium for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "78",
    name: "SketchUp",
    variant: "SketchUp Pro",
    duration: "1Y",
    category: "🛠 3D / CAD Engineering",
    description: "Premium access to SketchUp Pro for 1Y.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "",
    status: "Active"
  },
  {
    id: "79",
    name: "Windows 10",
    variant: "Windows 10 Pro",
    duration: "Lifetime",
    category: "🔐 Software Keys",
    description: "Premium access to Windows 10 Pro for Lifetime.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "Lifetime License",
    status: "Active"
  },
  {
    id: "80",
    name: "Windows 11",
    variant: "Windows 11 Pro",
    duration: "Lifetime",
    category: "🔐 Software Keys",
    description: "Premium access to Windows 11 Pro for Lifetime.",
    originalPrice: "199",
    discountPrice: "29",
    discountBadge: "85% OFF",
    badge: "Lifetime License",
    status: "Active"
  },
];
