export interface Tool {
    id: string;
    name: string;
    variant: string;
    duration: string;
    category: string;
    description: string;
    originalPrice: string | number;
    discountPrice: string | number;
    discountBadge: string;
    badge: string;
    status: string;
    image?: string;
}

export const TOOLS: Tool[] = [
    {
        "id": "1",
        "name": "CodeRabbit",
        "variant": "Pro",
        "duration": "1M",
        "category": "🔥 New & Premium",
        "description": "Get absolute premium access to CodeRabbit Pro for 1M. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "Trending",
        "status": "Active",
        "image": "https://2025.allthingsopen.org/wp-content/uploads/2025/07/Platinum_CodeRabbit.jpg"
    },
    // {
    //     "id": "2",
    //     "name": "CodeRabbit",
    //     "variant": "Pro",
    //     "duration": "2M",
    //     "category": "🔥 New & Premium",
    //     "description": "Get absolute premium access to CodeRabbit Pro for 2M. Perfect for scaling businesses, agencies, and top professionals.",
    //     "originalPrice": "199",
    //     "discountPrice": "29",
    //     "discountBadge": "85% OFF",
    //     "badge": "Trending",
    //     "status": "Active"
    // },
    {
        "id": "3",
        "name": "Loom Business + AI",
        "variant": "Business + AI",
        "duration": "1Y",
        "category": "🔥 New & Premium",
        "description": "Get absolute premium access to Loom Business + AI for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "Trending",
        "status": "Active"
    },
    {
        "id": "4",
        "name": "Wispr Flow",
        "variant": "Pro",
        "duration": "1Y",
        "category": "🔥 New & Premium",
        "description": "Get absolute premium access to Wispr Flow Pro for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "Trending",
        "status": "Active"
    },
    {
        "id": "5",
        "name": "Willow Voice",
        "variant": "Pro",
        "duration": "1Y",
        "category": "🔥 New & Premium",
        "description": "Get absolute premium access to Willow Voice Pro for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "Trending",
        "status": "Active",
        "image": "https://2025.allthingsopen.org/wp-content/uploads/2025/07/Platinum_CodeRabbit.jpg"
    },
    {
        "id": "6",
        "name": "PromptDrive.ai",
        "variant": "Teams",
        "duration": "1Y",
        "category": "🔥 New & Premium",
        "description": "Get absolute premium access to PromptDrive.ai Teams for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "Trending",
        "status": "Active"
    },
    {
        "id": "7",
        "name": "PromptDrive.ai Business (50 Seats)",
        "variant": "Pro",
        "duration": "1Y",
        "category": "🔥 New & Premium",
        "description": "Get absolute premium access to PromptDrive.ai Business (50 Seats) for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "Trending",
        "status": "Active"
    },
    {
        "id": "8",
        "name": "PostHog",
        "variant": "Scale",
        "duration": "1Y",
        "category": "🔥 New & Premium",
        "description": "Get absolute premium access to PostHog Scale for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "Trending",
        "status": "Active"
    },
    {
        "id": "9",
        "name": "Firecrawl",
        "variant": "AI",
        "duration": "50K Credits (1Y)",
        "category": "🔥 New & Premium",
        "description": "Get absolute premium access to Firecrawl AI for 50K Credits (1Y). Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "Trending",
        "status": "Active"
    },
    {
        "id": "10",
        "name": "Vapi",
        "variant": "Standard",
        "duration": "$200 Credits (12M)",
        "category": "🔥 New & Premium",
        "description": "Get absolute premium access to Vapi for $200 Credits (12M). Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "Trending",
        "status": "Active"
    },
    {
        "id": "11",
        "name": "Emergent Standard",
        "variant": "Standard",
        "duration": "1Y",
        "category": "🔥 New & Premium",
        "description": "Get absolute premium access to Emergent Standard for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "Trending",
        "status": "Active"
    },
    {
        "id": "12",
        "name": "Manus AI Pro (6000 Credits)",
        "variant": "Pro",
        "duration": "1M",
        "category": "🔥 New & Premium",
        "description": "Get absolute premium access to Manus AI Pro (6000 Credits) for 1M. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "Trending",
        "status": "Active"
    },
    {
        "id": "13",
        "name": "Reforge AI Build",
        "variant": "Standard",
        "duration": "1M",
        "category": "🔥 New & Premium",
        "description": "Get absolute premium access to Reforge AI Build for 1M. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "Trending",
        "status": "Active"
    },
    {
        "id": "14",
        "name": "Sentry.io",
        "variant": "Teams",
        "duration": "1Y",
        "category": "🔥 New & Premium",
        "description": "Get absolute premium access to Sentry.io Teams for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "Trending",
        "status": "Active"
    },
    {
        "id": "15",
        "name": "Sentry.io",
        "variant": "Business",
        "duration": "1Y",
        "category": "🔥 New & Premium",
        "description": "Get absolute premium access to Sentry.io Business for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "Trending",
        "status": "Active"
    },
    {
        "id": "16",
        "name": "Beautiful.ai",
        "variant": "Pro",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Beautiful.ai Pro for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "17",
        "name": "Mobbin",
        "variant": "Pro",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Mobbin Pro for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "18",
        "name": "ChatPRD",
        "variant": "Pro",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to ChatPRD Pro for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "19",
        "name": "Perplexity",
        "variant": "Pro",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Perplexity Pro for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "20",
        "name": "Raycast",
        "variant": "Pro",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Raycast Pro for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "21",
        "name": "Superhuman",
        "variant": "Starter",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Superhuman Starter for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "22",
        "name": "Linear",
        "variant": "Business",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Linear Business for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "23",
        "name": "Granola",
        "variant": "Business",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Granola Business for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "24",
        "name": "Magic Patterns Hobby",
        "variant": "Standard",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Magic Patterns Hobby for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "25",
        "name": "Webflow CMS",
        "variant": "Standard",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Webflow CMS for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "26",
        "name": "Webflow",
        "variant": "Business",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Webflow Business for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "27",
        "name": "Webflow",
        "variant": "Growth",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Webflow Growth for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "28",
        "name": "n8n",
        "variant": "Starter",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to n8n Starter for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "29",
        "name": "Replit",
        "variant": "Core",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Replit Core for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "30",
        "name": "Lovable Pro (100 Credits / Month)",
        "variant": "Pro",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Lovable Pro (100 Credits / Month) for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "31",
        "name": "ClickUp",
        "variant": "Enterprise",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to ClickUp Enterprise for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "32",
        "name": "Cal.com",
        "variant": "Teams",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Cal.com Teams for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "33",
        "name": "Cal.com",
        "variant": "Organization",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Cal.com Organization for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "34",
        "name": "GitLab",
        "variant": "Ultimate",
        "duration": "12M",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to GitLab Ultimate for 12M. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "35",
        "name": "Postman",
        "variant": "Basic",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Postman Basic for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "36",
        "name": "Zeplin",
        "variant": "Advanced",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Zeplin Advanced for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "37",
        "name": "Backblaze Cloud",
        "variant": "Unlimited",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Backblaze Cloud Unlimited for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "38",
        "name": "Bitwarden Premium +",
        "variant": "Family",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Bitwarden Premium + Family for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "39",
        "name": "Termly.io",
        "variant": "Starter",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Termly.io Starter for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "40",
        "name": "Termly.io",
        "variant": "Pro+",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Termly.io Pro+ for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "41",
        "name": "Hostinger Cloud",
        "variant": "Startup",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Hostinger Cloud Startup for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "42",
        "name": "Pica",
        "variant": "Starter",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Pica Starter for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "43",
        "name": "Framer",
        "variant": "Basic",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Framer Basic for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "44",
        "name": "Framer",
        "variant": "Pro",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Framer Pro for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "45",
        "name": "Figma",
        "variant": "Professional",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Figma Professional for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "46",
        "name": "Intercom",
        "variant": "Advanced",
        "duration": "1Y",
        "category": "⭐ Top Selling",
        "description": "Get absolute premium access to Intercom Advanced for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "47",
        "name": "Rezi",
        "variant": "AI",
        "duration": "Lifetime",
        "category": "🎓 Career / Education",
        "description": "Get absolute premium access to Rezi AI for Lifetime. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "48",
        "name": "PNGTree Premium",
        "variant": "Standard",
        "duration": "Lifetime",
        "category": "🎓 Career / Education",
        "description": "Get absolute premium access to PNGTree Premium for Lifetime. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "49",
        "name": "Enginemailer Free Forever (10K / Month)",
        "variant": "Standard",
        "duration": "Lifetime",
        "category": "🎓 Career / Education",
        "description": "Get absolute premium access to Enginemailer Free Forever (10K / Month) for Lifetime. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "50",
        "name": "LinkedIn Career Premium",
        "variant": "Standard",
        "duration": "3M",
        "category": "🎓 Career / Education",
        "description": "Get absolute premium access to LinkedIn Career Premium for 3M. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "51",
        "name": "LinkedIn Business Premium",
        "variant": "Standard",
        "duration": "3M",
        "category": "🎓 Career / Education",
        "description": "Get absolute premium access to LinkedIn Business Premium for 3M. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "52",
        "name": "Scrimba",
        "variant": "Pro",
        "duration": "1Y",
        "category": "🎓 Career / Education",
        "description": "Get absolute premium access to Scrimba Pro for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "53",
        "name": "No Code MBA",
        "variant": "Unlimited",
        "duration": "1M",
        "category": "🎓 Career / Education",
        "description": "Get absolute premium access to No Code MBA Unlimited for 1M. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "54",
        "name": "Whizlabs Premium",
        "variant": "Standard",
        "duration": "1M",
        "category": "🎓 Career / Education",
        "description": "Get absolute premium access to Whizlabs Premium for 1M. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "55",
        "name": "Whizlabs Premium",
        "variant": "Standard",
        "duration": "1Y",
        "category": "🎓 Career / Education",
        "description": "Get absolute premium access to Whizlabs Premium for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "56",
        "name": "AhaSlides Essentials",
        "variant": "Standard",
        "duration": "12M",
        "category": "🎓 Career / Education",
        "description": "Get absolute premium access to AhaSlides Essentials for 12M. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "57",
        "name": "AhaSlides",
        "variant": "Pro",
        "duration": "12M",
        "category": "🎓 Career / Education",
        "description": "Get absolute premium access to AhaSlides Pro for 12M. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "58",
        "name": "Kickresume Premium",
        "variant": "Standard",
        "duration": "1M",
        "category": "🎓 Career / Education",
        "description": "Get absolute premium access to Kickresume Premium for 1M. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "59",
        "name": "Mangoosh GRE Premium",
        "variant": "Standard",
        "duration": "1M",
        "category": "🎓 Career / Education",
        "description": "Get absolute premium access to Mangoosh GRE Premium for 1M. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "60",
        "name": "UFC FightPass",
        "variant": "Standard",
        "duration": "2M",
        "category": "🎓 Career / Education",
        "description": "Get absolute premium access to UFC FightPass for 2M. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "61",
        "name": "Gemini AI Pro + 2TB Storage",
        "variant": "Pro",
        "duration": "18M",
        "category": "🎓 Career / Education",
        "description": "Get absolute premium access to Gemini AI Pro + 2TB Storage for 18M. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "62",
        "name": "Adobe Creative Cloud",
        "variant": "Max",
        "duration": "1Y",
        "category": "🎨 AI & Design Tools",
        "description": "Get absolute premium access to Adobe Creative Cloud Max for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "63",
        "name": "Midjourney",
        "variant": "Pro",
        "duration": "1M",
        "category": "🎨 AI & Design Tools",
        "description": "Get absolute premium access to Midjourney Pro for 1M. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "64",
        "name": "Canva",
        "variant": "Creator",
        "duration": "Lifetime",
        "category": "🎨 AI & Design Tools",
        "description": "Get absolute premium access to Canva Creator for Lifetime. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "65",
        "name": "HubSpot",
        "variant": "Growth",
        "duration": "1Y",
        "category": "📈 Business & Marketing",
        "description": "Get absolute premium access to HubSpot Growth for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "66",
        "name": "Mailchimp Advanced (100K Credits)",
        "variant": "Standard",
        "duration": "1M",
        "category": "📈 Business & Marketing",
        "description": "Get absolute premium access to Mailchimp Advanced (100K Credits) for 1M. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "67",
        "name": "SEMrush Guru Plan",
        "variant": "Standard",
        "duration": "1Y",
        "category": "📈 Business & Marketing",
        "description": "Get absolute premium access to SEMrush Guru Plan for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "68",
        "name": "Google Drive 2TB Storage",
        "variant": "Standard",
        "duration": "1Y",
        "category": "☁️ Cloud & Storage",
        "description": "Get absolute premium access to Google Drive 2TB Storage for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "69",
        "name": "Dropbox Professional 3TB Storage",
        "variant": "Pro",
        "duration": "1Y",
        "category": "☁️ Cloud & Storage",
        "description": "Get absolute premium access to Dropbox Professional 3TB Storage for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "70",
        "name": "iCloud+ 2TB",
        "variant": "Standard",
        "duration": "1Y",
        "category": "☁️ Cloud & Storage",
        "description": "Get absolute premium access to iCloud+ 2TB for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "71",
        "name": "Jira Premium (Per Seat)",
        "variant": "Standard",
        "duration": "1Y",
        "category": "🧩 Dev & Team Tools",
        "description": "Get absolute premium access to Jira Premium (Per Seat) for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "72",
        "name": "GitHub Enterprise (Per Seat)",
        "variant": "Standard",
        "duration": "1Y",
        "category": "🧩 Dev & Team Tools",
        "description": "Get absolute premium access to GitHub Enterprise (Per Seat) for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "73",
        "name": "Slack Enterprise",
        "variant": "Grid",
        "duration": "1Y",
        "category": "🧩 Dev & Team Tools",
        "description": "Get absolute premium access to Slack Enterprise Grid for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "74",
        "name": "AutoCAD 2024",
        "variant": "Professional",
        "duration": "1Y",
        "category": "🛠 3D / CAD Engineering",
        "description": "Get absolute premium access to AutoCAD 2024 Professional for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "75",
        "name": "SolidWorks Premium",
        "variant": "Standard",
        "duration": "1Y",
        "category": "🛠 3D / CAD Engineering",
        "description": "Get absolute premium access to SolidWorks Premium for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "76",
        "name": "SketchUp",
        "variant": "Pro",
        "duration": "1Y",
        "category": "🛠 3D / CAD Engineering",
        "description": "Get absolute premium access to SketchUp Pro for 1Y. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "",
        "status": "Active"
    },
    {
        "id": "77",
        "name": "Windows 10",
        "variant": "Pro",
        "duration": "Lifetime",
        "category": "🔐 Software Keys",
        "description": "Get absolute premium access to Windows 10 Pro for Lifetime. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "Lifetime License",
        "status": "Active"
    },
    {
        "id": "78",
        "name": "Windows 11",
        "variant": "Pro",
        "duration": "Lifetime",
        "category": "🔐 Software Keys",
        "description": "Get absolute premium access to Windows 11 Pro for Lifetime. Perfect for scaling businesses, agencies, and top professionals.",
        "originalPrice": "199",
        "discountPrice": "29",
        "discountBadge": "85% OFF",
        "badge": "Lifetime License",
        "status": "Active"
    }
];